{% set name = "dtool_s3" %}
{% set reponame = "dtool-s3" %}
{% set author = "jic-dtool" %}
{% set version = "0.8.0" %}
{% set sha256 = "224585c30741d2fa4766f03aab28dc0f2e36bf4ae329cd352eaff16e9c6e16fd" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ author }}/{{ reponame }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  preserve_egg_dir: True
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - click
    - setuptools
    - dtoolcore
    - dtool_cli
    - boto3

test:
  imports:
    - dtool_s3
    - dtool_s3.storagebroker

about:
  home: http://github.com/{{ author }}/{{ reponame }}
  license: MIT
  license_file: LICENSE.rst
  summary: 'S3 support for dtool'

  dev_url: https://github.com/{{ author }}/{{ reponame }}

extra:
  recipe-maintainers:
    - pvanheus
