{% set name = "dtool_s3" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/dtool-s3/dtool-s3-{{ version }}.tar.gz
  sha256: 00b7a46268b02aea21c30e7ba215494c1330a477338890194abfc47dafafcf34

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - click
    - setuptools
    - dtoolcore
    - dtool_cli
    - boto3

test:
  imports:
    - dtool_s3
    - dtool_s3.storagebroker
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jic-dtool/dtool-s3
  license: MIT
  license_file: LICENSE.rst
  summary: S3 support for dtool
  doc_url: https://github.com/jic-dtool/dtool-s3
  dev_url: https://github.com/jic-dtool/dtool-s3

extra:
  recipe-maintainers:
    - pvanheus
    - jan-janssen
    - tjelvar-olsson
