travis:
  secure:
    BINSTAR_TOKEN: fEEWu4/GCW1x6H/BBJY1njNmhQj6/rQrFOGPseqNQGgtVjozEJft9jJqeELilOvFOIQYTerD1zHvBBW6OfjC1VG6wLkqDxbGe7M3d1U6dCYd4FlSQ7NvmA0RdpJs1yZgzcJUTebnBTpaShUhLufFWxs7OQsBiBP7lSZEqxEnvQu92ESHmuZ+9gApVFAWLm9umzV4TsI20zAkmEEx78sMGv41u3gywP+EpzyJzQyqBQlAWKT/2RAlbGO7VTMj347LocEpFivdE3YH9fD+bo+llEXmXZd2ErbmLsv5lTFrk+9KBrPgLVBUGu3Dv5QkrXIifEX9E5rzzxpZv5xstT/WTZhf8FmoUMGk/cFDx3Ihwo4K33z0QXEr4NoyZ40P2t0OJa/jso8+ruqEiRDh/XhSEtUn0lj5VMs4BKelLJr2W5v/lzC6w99qkYHBuZbUwYNWVoYME9yzdMGmOtVqNtTUbqqe/3rFtCAgu1r4hU5FojPy0wLlJwt0C8Di0TqIZuQwjOGyZBkr6yLX5iLiqAAoIwS437U4nEC5KQyhlAmWrV2spblLXjn//aZE2BWpiLd/RkPlsKWgZjr0UlKlov0oi+1X09daYskMh9ESfN7bSdd+fsdnJQOk0CwfIA6QqxitfHhPSI7uB1gczJwzF5pEPaYPLefHqsBMLpsodM8bPN8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
